### ISSUE TITLE
Looks like it doesn't work on my site

### ISSUE THREAD

**Issue by nhoizey** [bbody/fit-on-a-floppy#3]
I get an error when trying on https://nicolas-hoizey.com :

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/78213/69496614-49aab000-0ed4-11ea-8c1e-8ad31ec7ddba.png">

**Comment by bbody** [comment]
@nhoizey looks like it might be due to the next-gen image formats, I will look into it. Thank you for the feedback, will look into it

**Comment by nhoizey** [comment]
@bbody thanks. Nice idea, by the way! 👍

**Comment by bbody** [comment]
Fixed @nhoizey, can you confirm?

**Comment by nhoizey** [comment]
It works, indeed! 👍
